- name: Run vault container
  shell: |
    docker run -dit --cap-add=IPC_LOCK \
      -e 'VAULT_DEV_ROOT_TOKEN_ID={{ remote_vault_token }}' \
      --name 'tf_vault' \
      -p 8200:8200 \
      hashicorp/vault:latest
  register: vault_start
  ignore_errors: true
  failed_when: vault_start.rc != 0 and "already in use" not in vault_start.stderr
  become_user: "root"

- name: Wait for Vault to initialize
  pause:
    seconds: 60

- name: Set environment variables
  shell: |
    export TF_VAR_vault_address='{{ remote_vault_address }}'
    export TF_VAR_vault_token='{{ remote_vault_token }}'
    export TF_LOG=DEBUG

- name: Add 'ubuntu' user to the 'docker' group
  ansible.builtin.user:
    name: "ubuntu"
    groups: "docker"
    append: yes
  register: user_mod_result

- name: Reset connection to apply new group membership
  ansible.builtin.meta: reset_connection
  when: user_mod_result.changed

- name: Store test credentials
  shell: |
    docker exec tf_vault sh -c "
    export VAULT_ADDR='{{ remote_vault_address }}' && 
    vault login {{ remote_vault_token }} && 
    vault kv put secret/test username='test_user' password='1234'
    "
  register: test_result
  become: true
  become_user: "root"

- name: Store AWS credentials
  shell: |
    docker exec tf_vault sh -c "
    export VAULT_ADDR='{{ remote_vault_address }}' && 
    vault login {{ remote_vault_token }} && 
    vault kv put secret/aws access_key='{{ aws_access_key_id }}' secret_key='{{ aws_secret_access_key }}'
    "
  register: aws_result
  become_user: "root"

- name: Store Velero configuration
  shell: |
    docker exec tf_vault sh -c "
    export VAULT_ADDR='{{ remote_vault_address }}' && 
    vault login {{ remote_vault_token }} && 
    vault kv put secret/velero bucket_name='{{ velero_bucket_name }}' region='{{ velero_region }}'
    "
  register: velero_result
  become_user: "root"

- name: Store jenkins credentials
  shell: |
    docker exec -i tf_vault sh << EOF
    export VAULT_ADDR="http://127.0.0.1:8200"
    vault login {{ remote_vault_token }}
    vault kv put secret/jenkins -<<EOJSON
    {
      "jenkins_username": "{{ jenkins_username }}",
      "jenkins_password": "{{ jenkins_password }}"
    }
    EOJSON
    EOF
  register: jenkins_result
  become_user: "root"

- name: Store git credentials
  shell: |
    docker exec -i tf_vault sh << EOF
    export VAULT_ADDR="http://127.0.0.1:8200"
    vault login {{ remote_vault_token }}
    vault kv put secret/git_credentials -<<EOJSON
    {
      "git_username": "{{ git_username }}",
      "git_password": "{{ git_password }}"
    }
    EOJSON
    EOF
  register: git_result
  become_user: "root"

- name: Store docker credentials
  shell: |
    docker exec -i tf_vault sh << EOF
    export VAULT_ADDR="http://127.0.0.1:8200"
    vault login {{ remote_vault_token }}
    vault kv put secret/docker_credentials -<<EOJSON
    {
      "docker_username": "{{ docker_username }}",
      "docker_password": "{{ docker_password }}"
    }
    EOJSON
    EOF
  register: docker_result
  become_user: "root"

- name: Display setup status
  debug:
    msg: 
      - "Vault container setup complete"
      - "Access: {{ remote_vault_address }}"
      - "Token: {{ remote_vault_token }}"